### ISSUE TITLE
Update npm and node-red to use 1.0.3 version?

### ISSUE THREAD

**Issue by jdesai61** [sushilks/node-red-contrib-lutron#4]
Currently the node-red Palette and npm still refers to 1.0.2 version of this code (https://flows.nodered.org/node/node-red-contrib-lutron and https://www.npmjs.com/package/node-red-contrib-lutron).  As 1.0.3 has significant new functionality, it will be nice if those pages can refer to the latest version of code.  I myself installed 1.0.2 from the node-red Palette and fixing some issues until I realized that github latest release (1.0.3) fixed all my issues.  Thanks for a great node - very useful in my home automation.

**Comment by noumenon272** [comment]
seconded! please  please please put this in the palette! thanks

**Comment by sushilks** [comment]
I Published it on npm.
